/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

/**
 *
 * @author Ronald
 */
public class formularioMenuMovimientos extends javax.swing.JFrame {

    /**
     * Creates new form formularioMenuMovimientos
     */
    public formularioMenuMovimientos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butonCrearMovimiento = new javax.swing.JButton();
        butonVerMovimiento = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        butonEditarMovimiento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butonCrearMovimiento.setText("Crear Movimiento");
        butonCrearMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonCrearMovimientoActionPerformed(evt);
            }
        });

        butonVerMovimiento.setText("Movimientos");
        butonVerMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonVerMovimientoActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        butonEditarMovimiento.setText("Editar Movimientos");
        butonEditarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonEditarMovimientoActionPerformed(evt);
            }
        });

        jLabel1.setText("Movimientos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butonCrearMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonEditarMovimiento))
                        .addGap(40, 40, 40)
                        .addComponent(butonVerMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonCrearMovimiento)
                    .addComponent(butonVerMovimiento))
                .addGap(41, 41, 41)
                .addComponent(butonEditarMovimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonCrearMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonCrearMovimientoActionPerformed
        formularioMovimientoCrear obj = new formularioMovimientoCrear();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butonCrearMovimientoActionPerformed

    private void butonVerMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonVerMovimientoActionPerformed
        formularioMovimientoVisualizar obj = new formularioMovimientoVisualizar();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butonVerMovimientoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void butonEditarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonEditarMovimientoActionPerformed
        formularioMovimientoEditar obj = new formularioMovimientoEditar();

        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butonEditarMovimientoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton butonCrearMovimiento;
    private javax.swing.JButton butonEditarMovimiento;
    private javax.swing.JButton butonVerMovimiento;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
