/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Clases.EjecutarOperaciones;
import javax.swing.JOptionPane;


/**
 *
 * @author Ronald
 */
public class formularioPedidosVentas extends javax.swing.JFrame {

    /**
     * Creates new form formularioPedidosVentas
     */
    public formularioPedidosVentas() {
        initComponents();
        this.setLocationRelativeTo(null);
        EjecutarOperaciones.llenarComboNombreProducto(jComboNombreProducto);
        EjecutarOperaciones.llenarComboNombreUsuario(jComboNombreUsuario);
        EjecutarOperaciones.llenarComboNombreCliente(jComboNombreCLiente);
        txtFechaPedido.setDateFormatString("dd/MM/yyyy"); // Sirve para mostrar el formato en el date chooser

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jComboNombreUsuario = new javax.swing.JComboBox<>();
        lblNombreUsuario = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        jComboNombreProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        lblCodigoProducto = new javax.swing.JLabel();
        lblsetCodigoProducto = new javax.swing.JLabel();
        lblNombreUsuario1 = new javax.swing.JLabel();
        jComboNombreCLiente = new javax.swing.JComboBox<>();
        spinCantidad = new javax.swing.JSpinner();
        txtFechaPedido = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblNombreUsuario.setText("Nombre Usuario");

        lblNombreProducto.setText("Nombre Producto");

        jComboNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboNombreProductoActionPerformed(evt);
            }
        });

        jLabel3.setText("cantidad");

        jLabel4.setText("fecha pedido");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblCodigoProducto.setText("id producto");

        lblNombreUsuario1.setText("Nombre Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombreUsuario1)
                    .addComponent(lblCodigoProducto)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(lblNombreProducto)
                    .addComponent(lblNombreUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboNombreUsuario, javax.swing.GroupLayout.Alignment.LEADING, 0, 197, Short.MAX_VALUE)
                            .addComponent(jComboNombreCLiente, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jComboNombreProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblsetCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuario1)
                    .addComponent(jComboNombreCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProducto)
                    .addComponent(jComboNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCodigoProducto)
                    .addComponent(lblsetCodigoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnAgregar)
                        .addContainerGap(13, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre_producto = (jComboNombreProducto.getSelectedItem().toString());
        String codigo_producto = (lblsetCodigoProducto.getText().toString());
        String nombreUsuario = (jComboNombreUsuario.getSelectedItem().toString());
        String nombreCliente = (jComboNombreCLiente.getSelectedItem().toString());
        String fecha_pedido = "" + txtFechaPedido.getDate();
        int cantidadProducto = EjecutarOperaciones.calcularCantidadProducto(nombre_producto);
        int cantidad = (Integer) spinCantidad.getValue();
        String[] producto = EjecutarOperaciones.obtenerProducto(nombre_producto);

        if (cantidad <= cantidadProducto) {
            int precioUnitario = Integer.parseInt(producto[3]);
            float precioTotal = precioUnitario * cantidad;
            int idSucursal = Integer.parseInt(producto[5]);

            EjecutarOperaciones.aumentarMontoSucursal(precioTotal, idSucursal);

            EjecutarOperaciones.registrarPedido(nombreUsuario, nombreCliente, nombre_producto, codigo_producto, cantidad, fecha_pedido);
            cantidadProducto = cantidadProducto - cantidad;
            EjecutarOperaciones.restarUnidades(cantidadProducto, nombre_producto);
            JOptionPane.showMessageDialog(null, "Pedido realizado correctamente");
            int cantidadesRestantes = EjecutarOperaciones.calcularCantidadProducto(nombre_producto);
            if (cantidadesRestantes <= 20) {
                JOptionPane.showMessageDialog(null, "Hay menos de 20 unidades del producto que acaba de realizar pedido de venta.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay suficiente cantidad de este producto para realizar el pedido.");
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jComboNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboNombreProductoActionPerformed
        String nombre_producto = (jComboNombreProducto.getSelectedItem().toString());
        EjecutarOperaciones.llenarComboNombreProducto(nombre_producto, lblsetCodigoProducto);
    }//GEN-LAST:event_jComboNombreProductoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> jComboNombreCLiente;
    private javax.swing.JComboBox<String> jComboNombreProducto;
    private javax.swing.JComboBox<String> jComboNombreUsuario;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCodigoProducto;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblNombreUsuario1;
    private javax.swing.JLabel lblsetCodigoProducto;
    private javax.swing.JSpinner spinCantidad;
    private com.toedter.calendar.JDateChooser txtFechaPedido;
    // End of variables declaration//GEN-END:variables
}
